### ISSUE TITLE
Other questions ...

### ISSUE THREAD

**Issue by jphconstantin** [marcanuy/publishfeed#6]
Other points:

- the urls defined in feeds.yml is the url of the feed.xml or the url of the posts ?
- what shall I write in hashtags (I am not familiar with twitter ...)
- the app runs only with a github website ?
- once developped in a virtual python environment, what shall I publish on my site ? (a copy of the environment ?)

**Comment by marcanuy** [comment]
- the urls defined in feeds.yml is the url of the feed.xml or the url of the posts ?
  - the url of the Atom or RSS feed 
- what shall I write in hashtags (I am not familiar with twitter ...)
  - the word that is added to group content in Twitter
- the app runs only with a github website ?
  - you need to run it by your own in a custom environment
- once developped in a virtual python environment, what shall I publish on my site ? (a copy of the environment ?)
  - yes
