### ISSUE TITLE
After the tweepy correction ...

### ISSUE THREAD

**Issue by jphconstantin** [marcanuy/publishfeed#7]
OK. I corrected the requirements.txt file.
I executed `make install`

I executed (by hand, on my computer)  `python main.py f_f_meyrin --getfeeds` in `virtual_project/publishedfeed
`
Now I have in the databases folder a file called `rss_f_f_meyrin.db`

What else ?
Nothing is published by the app twitter, the keys and tokens are correct.

What is the name of the twitter handler ?
@f_f_meyrin ?
or
the name of the app twitter

Is it possible to "debug" or "log" because I don't know what happens ? I don't see how the app twitter is started.

> once developped in a virtual python environment, what shall I publish on my site ? (a copy of the environment ?)
> 
>     yes

You said yes. I copied my virtual_project folder in my repository:

```
virtual_project
 bin
 include
 lib
 lib64
 publishfeed
   databases
      rss_f_f_meyrin.db
  helper.py
  ...
  feeds.yml
  ...
  tests.py
  
 pyvenv.cfg
 share
```

That means my keys and tokens will be visible for everyone !!?

Are you still used this application in a website. I could compare what is missing ?

On your website `https://simpleit.rocks/web/automatically-tweet-new-blog-posts-based-in-rss/`, after **Install dependencies**,
the `Download feeds` part makes allusion to **feedr** but you never said if we also must install it !!???

feedr has also a main.py module ! and make allusion to databases folder !?

Shall I also installed feedr and use the main.py in this module but not this in publishedfeed ?

Sorry for my crazy question.

**Comment by jphconstantin** [comment]
It seems I must bump SQLAlchemy from 1.1.10 to 1.3.0 and PyYAML from 5.1 to 5.4 but 

Building wheels for collected packages: SQLAlchemy
  Running setup.py bdist_wheel for SQLAlchemy ... error
  Complete output from command /home/jpc/virtual-project/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/user/1000/pip-install-cy8x8dhq/SQLAlchemy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/user/1000/pip-wheel-m6rem1g2 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for SQLAlchemy

**Comment by jphconstantin** [comment]
I received this email:

The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: virtual-project/lib/python3.7/site-packages/setuptools/cli-32.exe, virtual-project/lib/python3.7/site-packages/setuptools/cli-64.exe, virtual-project/lib/python3.7/site-packages/setuptools/cli.exe, virtual-project/lib/python3.7/site-packages/setuptools/gui-32.exe, virtual-project/lib/python3.7/site-packages/setuptools/gui-64.exe, virtual-project/lib/python3.7/site-packages/setuptools/gui.exe, virtual-project/lib64/python3.7/site-packages/setuptools/cli-32.exe, virtual-project/lib64/python3.7/site-packages/setuptools/cli-64.exe, virtual-project/lib64/python3.7/site-packages/setuptools/cli.exe, virtual-project/lib64/python3.7/site-packages/setuptools/gui-32.exe, virtual-project/lib64/python3.7/site-packages/setuptools/gui-64.exe, and virtual-project/lib64/python3.7/site-packages/setuptools/gui.exe. For more information, see https://docs.github.com/github/administering-a-repository/about-releases.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request at https://support.github.com/contact?repo_id=272085590&page_build_id=243698831

**Comment by marcanuy** [comment]
> I executed (by hand, on my computer) `python main.py f_f_meyrin --getfeeds` in `virtual_project/publishedfeed `
Here you downloaded the list of URL's  your twitter account will be publishing.

> Now I have in the databases folder a file called `rss_f_f_meyrin.db`

This is the list of URL's downloaded in the above step, for example, for simpleit.rocks the feed url is: https://simpleit.rocks/index.xml where it gets the list of the articles.

Now you need to *tweet* each URL, for that we use the "--tweet" flag like:

`python main.py f_f_meyrin --tweet
`

When you run that command, it should tweet the URL, and mark it as published in the database, so the next time you execute the command it publishes the following unpublished URL.


> What is the name of the twitter handler ?
> @f_f_meyrin ?
> or
> the name of the app twitter

In your case would be **f_f_meyrin**

> > once developped in a virtual python environment, what shall I publish on my site ? (a copy of the environment ?)
It can run everywhere, if you set up cron jobs in a server it will detect new posts and tweet them automatically as explained in  the README file.


> 
> ```
> virtual_project
>  bin
>  include
>  lib
>  lib64
>  publishfeed
>    databases
>       rss_f_f_meyrin.db
>   helper.py
>   ...
>   feeds.yml
>   ...
>   tests.py
>   
>  pyvenv.cfg
>  share
> ```
> 
Source files shouldn't be at the same level of the virtual environment, I thought you meant to have them in the same server, this really depends on your configuration.

> That means my keys and tokens will be visible for everyone !!?
That depends how you set the permissions of the feed files or your environment, an improvement to this app would be to use environment variables instead of having them on that file, **anyone with access to that file would be able to read the credentials**.

> Shall I also installed feedr and use the main.py in this module but not this in publishedfeed ?
> 
No

Hope it helps
